[package]
name = "macroquad-game"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { version = "0.4.4", features = ["default"] }
image = "0.24.7"
rodio ="0.17.1"